name: ci
on: [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t hello-api .
      - name: Health check
        run: |
          docker run -d -p 8000:8000 --name app hello-api
          sleep 2
          curl -sf http://127.0.0.1:8000/healthz
